//
//  MobileListModels.swift
//  MPBG
//
//  Created by Pipat Shuleepongchad on 2/7/2562 BE.
//  Copyright (c) 2562 Pipat Shuleepongchad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MobileList
{
  // MARK: Use cases
  
  struct DisplayedMobile
  {
    var id: Int
    var name: String
    var description: String
    var thumbImageURL: String
    var price: String
    var rating: String
    var isFavourite: Bool
  }
    
  enum FetchMobiles
  {
    struct Request
    {
      var displayMethod: DisplayMethod?
      var sortMethod: SortMethod?
      init(displayMethod: DisplayMethod? = nil, sortMethod: SortMethod? = nil)
      {
        self.displayMethod = displayMethod
        self.sortMethod = sortMethod
      }
    }
    
    struct Response
    {
      var displayMethod: DisplayMethod
      var sortMethod: SortMethod
      var mobiles: [Mobile]
      var favouriteMobiles: [Mobile]
    }
    
    struct ViewModel
    {
      var displayMethod: DisplayMethod
      var sortMethod: SortMethod
      var displayedMobiles: [DisplayedMobile]
    }
  }
  
  enum AddFavourite
  {
    struct Request
    {
      var id: Int
    }
    
    struct Response
    {
      var mobile: Mobile
    }
    
    struct ViewModel
    {
      var id: Int
    }
  }
  
  enum DeleteFavourite
  {
    struct Request
    {
      var id: Int
    }
    
    struct Response
    {
      var displayMethod: DisplayMethod
      var mobile: Mobile
    }
    
    struct ViewModel
    {
      var displayMethod: DisplayMethod
      var id: Int
    }
  }
  
  enum Error
  {
    struct Response
    {
      let error: DataError
    }
    struct ViewModel
    {
      let title: String
      let message: String?
    }
  }

  
  enum Progress
  {
    struct Response
    {
      let show: Bool
    }
    
    struct ViewModel
    {
      let show: Bool
    }
  }
}
