//
//  MobileDetailPresenter.swift
//  MPBG
//
//  Created by Pipat Shuleepongchad on 4/7/2562 BE.
//  Copyright (c) 2562 Pipat Shuleepongchad. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MobileDetailPresentationLogic
{
  func presentMobile(response: MobileDetail.GetMobile.Response)
  func presentFetchedMobileImages(response: MobileDetail.FetchMobileImages.Response)
}

class MobileDetailPresenter: MobileDetailPresentationLogic
{
  weak var viewController: MobileDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentMobile(response: MobileDetail.GetMobile.Response)
  {
    let mobile = response.mobile
    let viewModel = MobileDetail.GetMobile.ViewModel(name: mobile.name, description: mobile.description, price: "$\(mobile.price)", rating: "\(mobile.rating)")
    viewController?.displayMobile(viewModel: viewModel)
  }
  
  func presentFetchedMobileImages(response: MobileDetail.FetchMobileImages.Response)
  {
    let images = response.mobileImages.map { $0.url }
    let viewModel = MobileDetail.FetchMobileImages.ViewModel(images: images)
    viewController?.displayFetchedMobileImages(viewModel: viewModel)
  }
}
